
package solis;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "solis_hipotenusa", targetNamespace = "http://solis/", wsdlLocation = "http://localhost:8080/solis_web_parcial1/solis_hipotenusa?wsdl")
public class SolisHipotenusa_Service
    extends Service
{

    private static final URL SOLISHIPOTENUSA_WSDL_LOCATION;
    private static final WebServiceException SOLISHIPOTENUSA_EXCEPTION;
    private static final QName SOLISHIPOTENUSA_QNAME = new QName("http://solis/", "solis_hipotenusa");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/solis_web_parcial1/solis_hipotenusa?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOLISHIPOTENUSA_WSDL_LOCATION = url;
        SOLISHIPOTENUSA_EXCEPTION = e;
    }

    public SolisHipotenusa_Service() {
        super(__getWsdlLocation(), SOLISHIPOTENUSA_QNAME);
    }

    public SolisHipotenusa_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOLISHIPOTENUSA_QNAME, features);
    }

    public SolisHipotenusa_Service(URL wsdlLocation) {
        super(wsdlLocation, SOLISHIPOTENUSA_QNAME);
    }

    public SolisHipotenusa_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOLISHIPOTENUSA_QNAME, features);
    }

    public SolisHipotenusa_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SolisHipotenusa_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SolisHipotenusa
     */
    @WebEndpoint(name = "solis_hipotenusaPort")
    public SolisHipotenusa getSolisHipotenusaPort() {
        return super.getPort(new QName("http://solis/", "solis_hipotenusaPort"), SolisHipotenusa.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SolisHipotenusa
     */
    @WebEndpoint(name = "solis_hipotenusaPort")
    public SolisHipotenusa getSolisHipotenusaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://solis/", "solis_hipotenusaPort"), SolisHipotenusa.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOLISHIPOTENUSA_EXCEPTION!= null) {
            throw SOLISHIPOTENUSA_EXCEPTION;
        }
        return SOLISHIPOTENUSA_WSDL_LOCATION;
    }

}
