package solis;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "solis_hipotenusa", targetNamespace = "http://solis/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SolisHipotenusa {


    /**
     * 
     * @param cateto1
     * @param cateto2
     * @return
     *     returns double
     */
    @WebMethod(operationName = "calcular_hipotenusa")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calcular_hipotenusa", targetNamespace = "http://solis/", className = "solis.CalcularHipotenusa")
    @ResponseWrapper(localName = "calcular_hipotenusaResponse", targetNamespace = "http://solis/", className = "solis.CalcularHipotenusaResponse")
    @Action(input = "http://solis/solis_hipotenusa/calcular_hipotenusaRequest", output = "http://solis/solis_hipotenusa/calcular_hipotenusaResponse")
    public double calcularHipotenusa(
        @WebParam(name = "cateto1", targetNamespace = "")
        double cateto1,
        @WebParam(name = "cateto2", targetNamespace = "")
        double cateto2);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "solis_garcia_jasiel")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "solis_garcia_jasiel", targetNamespace = "http://solis/", className = "solis.SolisGarciaJasiel")
    @ResponseWrapper(localName = "solis_garcia_jasielResponse", targetNamespace = "http://solis/", className = "solis.SolisGarciaJasielResponse")
    @Action(input = "http://solis/solis_hipotenusa/solis_garcia_jasielRequest", output = "http://solis/solis_hipotenusa/solis_garcia_jasielResponse")
    public String solisGarciaJasiel(
        @WebParam(name = "name", targetNamespace = "")
        String name);

}
